<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Hello.proto

namespace App\ProtoBuf\Hello;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.ProtoBuf.Hello.Hello</code>
 */
class Hello extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    protected $Name = '';
    /**
     * Generated from protobuf field <code>string Text = 3;</code>
     */
    protected $Text = '';
    /**
     * Generated from protobuf field <code>string Des = 2;</code>
     */
    protected $Des = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *     @type string $Text
     *     @type string $Des
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Hello::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Text = 3;</code>
     * @return string
     */
    public function getText()
    {
        return $this->Text;
    }

    /**
     * Generated from protobuf field <code>string Text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->Text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Des = 2;</code>
     * @return string
     */
    public function getDes()
    {
        return $this->Des;
    }

    /**
     * Generated from protobuf field <code>string Des = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDes($var)
    {
        GPBUtil::checkString($var, True);
        $this->Des = $var;

        return $this;
    }

}

